// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

use crate::sub_packet::*;

#[derive(Debug, Clone, PartialEq)]
pub struct InerPacket {
    pub field_u_32: u32,
    pub field_i_16_list: Vec<i16>,
}

impl BinaryCodec for InerPacket {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u32_le(self.field_u_32);
        put_list_le::<i16, u16>(buf, &self.field_i_16_list);
    }

    fn decode(buf: &mut Bytes) -> Option<InerPacket> {
        let field_u_32 = buf.get_u32_le();
        let field_i_16_list = get_list_le::<i16, u16>(buf)?;
        Some(Self {
            field_u_32,
            field_i_16_list,
        })
    }
}

#[cfg(test)]
mod iner_packet_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_iner_packet_codec() {
        let original = InerPacket {
            field_u_32: 123456,
            field_i_16_list: vec![-1234, -4321],
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = InerPacket::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct NestedPacket {
    pub sub_packet: SubPacket,
    pub sub_packet_list: Vec<SubPacket>,
    pub iner_packet: InerPacket,
}

impl BinaryCodec for NestedPacket {
    fn encode(&self, buf: &mut BytesMut) {
        self.sub_packet.encode(buf);
        put_object_list_le::<SubPacket, u16>(buf, &self.sub_packet_list);
        self.iner_packet.encode(buf);
    }

    fn decode(buf: &mut Bytes) -> Option<NestedPacket> {
        let sub_packet = SubPacket::decode(buf)?;
        let sub_packet_list = get_object_list_le::<SubPacket, u16>(buf)?;
        let iner_packet = InerPacket::decode(buf)?;
        Some(Self {
            sub_packet,
            sub_packet_list,
            iner_packet,
        })
    }
}

#[cfg(test)]
mod nested_packet_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_nested_packet_codec() {
        let original = NestedPacket {
            sub_packet: SubPacket {
                field_u_32: 123456,
                field_i_16_list: vec![-1234, -4321],
            },
            sub_packet_list: vec![],
            iner_packet: InerPacket {
                field_u_32: 123456,
                field_i_16_list: vec![-1234, -4321],
            },
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = NestedPacket::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
