// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct ExecutionReport {
    pub cl_ord_id: String,
    pub ord_cnfm_id: String,
    pub last_px: u64,
    pub last_qty: u64,
    pub ord_status: char,
}

impl BinaryCodec for ExecutionReport {
    fn encode(&self, buf: &mut BytesMut) {
        put_string::<u32>(buf, &self.cl_ord_id);
        put_string::<u32>(buf, &self.ord_cnfm_id);
        buf.put_u64(self.last_px);
        buf.put_u64(self.last_qty);
        put_char(buf, self.ord_status);
    }

    fn decode(buf: &mut Bytes) -> Option<ExecutionReport> {
        let cl_ord_id = get_string::<u32>(buf)?;
        let ord_cnfm_id = get_string::<u32>(buf)?;
        let last_px = buf.get_u64();
        let last_qty = buf.get_u64();
        let ord_status = get_char(buf)?;
        Some(Self {
            cl_ord_id,
            ord_cnfm_id,
            last_px,
            last_qty,
            ord_status,
        })
    }
}

#[cfg(test)]
mod execution_report_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_execution_report_codec() {
        let original = ExecutionReport {
            cl_ord_id: "example".to_string(),
            ord_cnfm_id: "example".to_string(),
            last_px: 123456789,
            last_qty: 123456789,
            ord_status: 'a',
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = ExecutionReport::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
