// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use byteorder::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

use crate::cancel_reject::*;
use crate::execution_report::*;
use crate::new_order::*;
use crate::order_cancel::*;
use crate::order_confirm::*;
use crate::risk_result::*;

#[derive(Debug, Clone, PartialEq)]
pub enum RcBinaryBodyEnum {
    NewOrder(NewOrder),
    OrderConfirm(OrderConfirm),
    ExecutionReport(ExecutionReport),
    OrderCancel(OrderCancel),
    CancelReject(CancelReject),
    RiskResult(RiskResult),
}

#[derive(Debug, Clone, PartialEq)]
pub struct RcBinary {
    pub msg_type: u32,
    pub version: u32,
    pub msg_body_len: u32,
    pub body: RcBinaryBodyEnum,
}

impl BinaryCodec for RcBinary {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u32(self.msg_type);
        buf.put_u32(self.version);
        let msg_body_len_pos = buf.len();
        buf.put_u32(0);

        let body_start = buf.len();
        match &self.body {
            RcBinaryBodyEnum::NewOrder(msg) => msg.encode(buf),
            RcBinaryBodyEnum::OrderConfirm(msg) => msg.encode(buf),
            RcBinaryBodyEnum::ExecutionReport(msg) => msg.encode(buf),
            RcBinaryBodyEnum::OrderCancel(msg) => msg.encode(buf),
            RcBinaryBodyEnum::CancelReject(msg) => msg.encode(buf),
            RcBinaryBodyEnum::RiskResult(msg) => msg.encode(buf),
        }
        let body_end = buf.len();
        BigEndian::write_u32(
            &mut buf[msg_body_len_pos..msg_body_len_pos + 4],
            (body_end - body_start) as u32,
        );
    }

    fn decode(buf: &mut Bytes) -> Option<RcBinary> {
        let msg_type = buf.get_u32();
        let version = buf.get_u32();
        let msg_body_len = buf.get_u32();
        let body = match msg_type {
            100101 => RcBinaryBodyEnum::NewOrder(NewOrder::decode(buf)?),
            200102 => RcBinaryBodyEnum::OrderConfirm(OrderConfirm::decode(buf)?),
            200115 => RcBinaryBodyEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            190007 => RcBinaryBodyEnum::OrderCancel(OrderCancel::decode(buf)?),
            290008 => RcBinaryBodyEnum::CancelReject(CancelReject::decode(buf)?),
            800001 => RcBinaryBodyEnum::RiskResult(RiskResult::decode(buf)?),
            _ => return None,
        };
        Some(Self {
            msg_type,
            version,
            msg_body_len,
            body,
        })
    }
}

#[cfg(test)]
mod rc_binary_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_rc_binary_codec() {
        let mut original = RcBinary {
            version: 123456,
            msg_body_len: 0,
            msg_type: 100101,
            body: RcBinaryBodyEnum::NewOrder(NewOrder {
                unique_order_id: "example".to_string(),
                cl_ord_id: "example".to_string(),
                security_id: "example".to_string(),
                side: vec!['a'; 1].into_iter().collect::<String>(),
                price: 123456789,
                order_qty: 123456789,
                ord_type: vec!['a'; 1].into_iter().collect::<String>(),
                account: "example".to_string(),
            }),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = RcBinary::decode(&mut bytes).unwrap();
        original.msg_body_len = decoded.msg_body_len;
        assert_eq!(original, decoded);
    }
}
