// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct ConfirmExtend041 {}

impl BinaryCodec for ConfirmExtend041 {
    fn encode(&self, _buf: &mut BytesMut) {}

    fn decode(_buf: &mut Bytes) -> Option<ConfirmExtend041> {
        Some(Self {})
    }
}

#[cfg(test)]
mod confirm_extend_041_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_confirm_extend_041_codec() {
        let original = ConfirmExtend041 {};

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = ConfirmExtend041::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
