// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct ExtendNewOrder043 {}

impl BinaryCodec for ExtendNewOrder043 {
    fn encode(&self, _buf: &mut BytesMut) {}

    fn decode(_buf: &mut Bytes) -> Option<ExtendNewOrder043> {
        Some(Self {})
    }
}

#[cfg(test)]
mod extend_new_order_043_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_extend_new_order_043_codec() {
        let original = ExtendNewOrder043 {};

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = ExtendNewOrder043::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
