// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

use crate::quote_response_extend_070::*;

#[derive(Debug, Clone, PartialEq)]
pub enum QuoteResponseApplExtendEnum {
    QuoteResponseExtend070(QuoteResponseExtend070),
}

#[derive(Debug, Clone, PartialEq)]
pub struct Quote2 {
    pub quote_id: String,
    pub quote_price: i64,
    pub quote_qty: i64,
}

impl BinaryCodec for Quote2 {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.quote_id, 10);
        buf.put_i64_le(self.quote_price);
        buf.put_i64_le(self.quote_qty);
    }

    fn decode(buf: &mut Bytes) -> Option<Quote2> {
        let quote_id = get_char_array(buf, 10)?;
        let quote_price = buf.get_i64_le();
        let quote_qty = buf.get_i64_le();
        Some(Self {
            quote_id,
            quote_price,
            quote_qty,
        })
    }
}

#[cfg(test)]
mod quote_2_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_quote_2_codec() {
        let original = Quote2 {
            quote_id: vec!['a'; 10].into_iter().collect::<String>(),
            quote_price: -123456789,
            quote_qty: -123456789,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Quote2::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct QuoteResponse {
    pub appl_id: String,
    pub reporting_pbuid: String,
    pub submitting_pbuid: String,
    pub security_id: String,
    pub security_id_source: String,
    pub owner_type: u16,
    pub clearing_firm: String,
    pub transact_time: i64,
    pub user_info: String,
    pub cl_ord_id: String,
    pub account_id: String,
    pub branch_id: String,
    pub quote_resp_id: String,
    pub quote_resp_type: u8,
    pub side: String,
    pub valid_until_time: i64,
    pub quote_type: u8,
    pub price_type: u8,
    pub quote_2: Vec<Quote2>,
    pub appl_extend: QuoteResponseApplExtendEnum,
}

impl BinaryCodec for QuoteResponse {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.appl_id, 3);
        put_char_array(buf, &self.reporting_pbuid, 6);
        put_char_array(buf, &self.submitting_pbuid, 6);
        put_char_array(buf, &self.security_id, 8);
        put_char_array(buf, &self.security_id_source, 4);
        buf.put_u16_le(self.owner_type);
        put_char_array(buf, &self.clearing_firm, 2);
        buf.put_i64_le(self.transact_time);
        put_char_array(buf, &self.user_info, 32);
        put_char_array(buf, &self.cl_ord_id, 10);
        put_char_array(buf, &self.account_id, 10);
        put_char_array(buf, &self.branch_id, 2);
        put_char_array(buf, &self.quote_resp_id, 10);
        buf.put_u8(self.quote_resp_type);
        put_char_array(buf, &self.side, 1);
        buf.put_i64_le(self.valid_until_time);
        buf.put_u8(self.quote_type);
        buf.put_u8(self.price_type);
        put_object_list_le::<Quote2, u16>(buf, &self.quote_2);
        match &self.appl_extend {
            QuoteResponseApplExtendEnum::QuoteResponseExtend070(msg) => msg.encode(buf),
        }
    }

    fn decode(buf: &mut Bytes) -> Option<QuoteResponse> {
        let appl_id = get_char_array(buf, 3)?;
        let reporting_pbuid = get_char_array(buf, 6)?;
        let submitting_pbuid = get_char_array(buf, 6)?;
        let security_id = get_char_array(buf, 8)?;
        let security_id_source = get_char_array(buf, 4)?;
        let owner_type = buf.get_u16_le();
        let clearing_firm = get_char_array(buf, 2)?;
        let transact_time = buf.get_i64_le();
        let user_info = get_char_array(buf, 32)?;
        let cl_ord_id = get_char_array(buf, 10)?;
        let account_id = get_char_array(buf, 10)?;
        let branch_id = get_char_array(buf, 2)?;
        let quote_resp_id = get_char_array(buf, 10)?;
        let quote_resp_type = buf.get_u8();
        let side = get_char_array(buf, 1)?;
        let valid_until_time = buf.get_i64_le();
        let quote_type = buf.get_u8();
        let price_type = buf.get_u8();
        let quote_2 = get_object_list_le::<Quote2, u16>(buf)?;
        let appl_extend = match appl_id.as_str() {
            "070" => QuoteResponseApplExtendEnum::QuoteResponseExtend070(
                QuoteResponseExtend070::decode(buf)?,
            ),
            _ => return None,
        };
        Some(Self {
            appl_id,
            reporting_pbuid,
            submitting_pbuid,
            security_id,
            security_id_source,
            owner_type,
            clearing_firm,
            transact_time,
            user_info,
            cl_ord_id,
            account_id,
            branch_id,
            quote_resp_id,
            quote_resp_type,
            side,
            valid_until_time,
            quote_type,
            price_type,
            quote_2,
            appl_extend,
        })
    }
}

#[cfg(test)]
mod quote_response_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_quote_response_codec() {
        let original = QuoteResponse {
            reporting_pbuid: vec!['a'; 6].into_iter().collect::<String>(),
            submitting_pbuid: vec!['a'; 6].into_iter().collect::<String>(),
            security_id: vec!['a'; 8].into_iter().collect::<String>(),
            security_id_source: vec!['a'; 4].into_iter().collect::<String>(),
            owner_type: 1234,
            clearing_firm: vec!['a'; 2].into_iter().collect::<String>(),
            transact_time: -123456789,
            user_info: vec!['a'; 32].into_iter().collect::<String>(),
            cl_ord_id: vec!['a'; 10].into_iter().collect::<String>(),
            account_id: vec!['a'; 10].into_iter().collect::<String>(),
            branch_id: vec!['a'; 2].into_iter().collect::<String>(),
            quote_resp_id: vec!['a'; 10].into_iter().collect::<String>(),
            quote_resp_type: 42,
            side: vec!['a'; 1].into_iter().collect::<String>(),
            valid_until_time: -123456789,
            quote_type: 42,
            price_type: 42,
            quote_2: vec![],
            appl_id: "070".to_string(),
            appl_extend: QuoteResponseApplExtendEnum::QuoteResponseExtend070(
                QuoteResponseExtend070 {
                    cash_margin: vec!['a'; 1].into_iter().collect::<String>(),
                },
            ),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = QuoteResponse::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
