// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct QuoteExtend071 {}

impl BinaryCodec for QuoteExtend071 {
    fn encode(&self, _buf: &mut BytesMut) {}

    fn decode(_buf: &mut Bytes) -> Option<QuoteExtend071> {
        Some(Self {})
    }
}

#[cfg(test)]
mod quote_extend_071_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_quote_extend_071_codec() {
        let original = QuoteExtend071 {};

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = QuoteExtend071::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
