// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct ReportExtend040 {
    pub cash_margin: String,
}

impl BinaryCodec for ReportExtend040 {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.cash_margin, 1);
    }

    fn decode(buf: &mut Bytes) -> Option<ReportExtend040> {
        let cash_margin = get_char_array(buf, 1)?;
        Some(Self { cash_margin })
    }
}

#[cfg(test)]
mod report_extend_040_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_report_extend_040_codec() {
        let original = ReportExtend040 {
            cash_margin: vec!['a'; 1].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = ReportExtend040::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
