// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct TradeCaptureReportAckExtend061 {}

impl BinaryCodec for TradeCaptureReportAckExtend061 {
    fn encode(&self, _buf: &mut BytesMut) {}

    fn decode(_buf: &mut Bytes) -> Option<TradeCaptureReportAckExtend061> {
        Some(Self {})
    }
}

#[cfg(test)]
mod trade_capture_report_ack_extend_061_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_trade_capture_report_ack_extend_061_codec() {
        let original = TradeCaptureReportAckExtend061 {};

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = TradeCaptureReportAckExtend061::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
