// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct TradeCaptureReportExtend060 {}

impl BinaryCodec for TradeCaptureReportExtend060 {
    fn encode(&self, _buf: &mut BytesMut) {}

    fn decode(_buf: &mut Bytes) -> Option<TradeCaptureReportExtend060> {
        Some(Self {})
    }
}

#[cfg(test)]
mod trade_capture_report_extend_060_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_trade_capture_report_extend_060_codec() {
        let original = TradeCaptureReportExtend060 {};

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = TradeCaptureReportExtend060::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
