// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

use crate::business_reject::*;
use crate::cancel_reject::*;
use crate::execution_confirm::*;
use crate::execution_report::*;
use crate::heartbeat::*;
use crate::logon::*;
use crate::logout::*;
use crate::new_order::*;
use crate::order_cancel_request::*;
use crate::platform_partition::*;
use crate::platform_state_info::*;
use crate::report_finished::*;
use crate::report_synchronization::*;
use crate::trading_session_status::*;

#[derive(Debug, Clone, PartialEq)]
pub enum SzseBinaryMsgTypeEnum {
    Logon(Logon),
    Logout(Logout),
    Heartbeat(Heartbeat),
    BusinessReject(BusinessReject),
    ReportSynchronization(ReportSynchronization),
    PlatformStateInfo(PlatformStateInfo),
    ReportFinished(ReportFinished),
    PlatformPartition(PlatformPartition),
    TradingSessionStatus(TradingSessionStatus),
    NewOrder(NewOrder),
    ExecutionConfirm(ExecutionConfirm),
    ExecutionReport(ExecutionReport),
    OrderCancelRequest(OrderCancelRequest),
    CancelReject(CancelReject),
}

#[derive(Debug, Clone, PartialEq)]
pub struct SzseBinary {
    pub msg_type: u32,
    pub body_length: u32,
    pub msg_type_body: SzseBinaryMsgTypeEnum,
    pub checksum: i32,
}

impl BinaryCodec for SzseBinary {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_u32(self.msg_type);
        buf.put_u32(self.body_length);
        match &self.msg_type_body {
            SzseBinaryMsgTypeEnum::Logon(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::Logout(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::Heartbeat(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::BusinessReject(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::ReportSynchronization(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::PlatformStateInfo(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::ReportFinished(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::PlatformPartition(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::TradingSessionStatus(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::NewOrder(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::ExecutionConfirm(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::ExecutionReport(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::OrderCancelRequest(msg) => msg.encode(buf),
            SzseBinaryMsgTypeEnum::CancelReject(msg) => msg.encode(buf),
        }
        buf.put_i32(self.checksum);
    }

    fn decode(buf: &mut Bytes) -> Option<SzseBinary> {
        let msg_type = buf.get_u32();
        let body_length = buf.get_u32();
        let msg_type_body = match msg_type {
            1 => SzseBinaryMsgTypeEnum::Logon(Logon::decode(buf)?),
            2 => SzseBinaryMsgTypeEnum::Logout(Logout::decode(buf)?),
            3 => SzseBinaryMsgTypeEnum::Heartbeat(Heartbeat::decode(buf)?),
            4 => SzseBinaryMsgTypeEnum::BusinessReject(BusinessReject::decode(buf)?),
            5 => SzseBinaryMsgTypeEnum::ReportSynchronization(ReportSynchronization::decode(buf)?),
            6 => SzseBinaryMsgTypeEnum::PlatformStateInfo(PlatformStateInfo::decode(buf)?),
            7 => SzseBinaryMsgTypeEnum::ReportFinished(ReportFinished::decode(buf)?),
            9 => SzseBinaryMsgTypeEnum::PlatformPartition(PlatformPartition::decode(buf)?),
            10 => SzseBinaryMsgTypeEnum::TradingSessionStatus(TradingSessionStatus::decode(buf)?),
            100101 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            100201 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            100301 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            100401 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            100501 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            100601 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            100701 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            101201 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            101301 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            101401 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            101501 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            101601 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            101701 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            101801 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            101901 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            102301 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            102701 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            102801 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            102901 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            103101 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            106301 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            103301 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            103501 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            103701 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            104101 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            104128 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            104701 => SzseBinaryMsgTypeEnum::NewOrder(NewOrder::decode(buf)?),
            200102 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            200202 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            200302 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            200402 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            200502 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            200602 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            200702 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            201202 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            201302 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            201402 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            201502 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            201602 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            201702 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            201802 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            201902 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            202202 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            202302 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            202702 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            202802 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            202902 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            203102 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            206302 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            203302 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            203502 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            203702 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            204102 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            204129 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            204702 => SzseBinaryMsgTypeEnum::ExecutionConfirm(ExecutionConfirm::decode(buf)?),
            200115 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            200215 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            200315 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            200415 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            200515 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            200615 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            200715 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            206315 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            203715 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            204115 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            204130 => SzseBinaryMsgTypeEnum::ExecutionReport(ExecutionReport::decode(buf)?),
            190007 => SzseBinaryMsgTypeEnum::OrderCancelRequest(OrderCancelRequest::decode(buf)?),
            290008 => SzseBinaryMsgTypeEnum::CancelReject(CancelReject::decode(buf)?),
            _ => return None,
        };
        let checksum = buf.get_i32();
        Some(Self {
            msg_type,
            body_length,
            msg_type_body,
            checksum,
        })
    }
}

#[cfg(test)]
mod szse_binary_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_szse_binary_codec() {
        let original = SzseBinary {
            body_length: 123456,
            msg_type: 1,
            msg_type_body: SzseBinaryMsgTypeEnum::Logon(Logon {
                sender_comp_id: vec!['a'; 20].into_iter().collect::<String>(),
                target_comp_id: vec!['a'; 20].into_iter().collect::<String>(),
                heart_bt_int: -123456,
                password: vec!['a'; 16].into_iter().collect::<String>(),
                default_appl_ver_id: vec!['a'; 32].into_iter().collect::<String>(),
            }),
            checksum: -123456,
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = SzseBinary::decode(&mut bytes).unwrap();

        assert_eq!(original, decoded);
    }
}
